import type { GameSettings } from '../game/types'
import { OverlayDialog } from './OverlayDialog'

type SettingsDialogProps = { settings: GameSettings; onChange: (settings: GameSettings) => void; onTutorial: () => void; onAbout: () => void; onClearStatistics: () => void; onClose: () => void }
export function SettingsDialog({ settings, onChange, onTutorial, onAbout, onClearStatistics, onClose }: SettingsDialogProps) {
  const change = <K extends keyof GameSettings>(key: K, value: GameSettings[K]) => onChange({ ...settings, [key]: value })
  const changeAnimationIntensity = (value: GameSettings['animationIntensity']) => onChange({ ...settings, animationIntensity: value, animationsEnabled: value !== 'off' })
  return <OverlayDialog label="遊戲設定" onClose={onClose}><p className="eyebrow">SETTINGS</p><h2>遊戲設定</h2><div className="settings-list"><label><span>音效</span><input type="checkbox" checked={settings.soundEnabled} onChange={(event) => change('soundEnabled', event.target.checked)} /></label><label><span>音量 <output>{Math.round(settings.volume * 100)}%</output></span><input aria-label="音量" type="range" min="0" max="1" step="0.05" value={settings.volume} onChange={(event) => change('volume', Number(event.target.value))} /></label><label><span>動畫強度</span><select aria-label="動畫強度" value={settings.animationIntensity} onChange={(event) => changeAnimationIntensity(event.target.value as GameSettings['animationIntensity'])}><option value="full">完整</option><option value="reduced">減少</option><option value="off">關閉</option></select></label><label><span>低刺激模式</span><input type="checkbox" checked={settings.lowStimulus} onChange={(event) => change('lowStimulus', event.target.checked)} /></label><label><span>觸覺回饋</span><input type="checkbox" checked={settings.hapticsEnabled} onChange={(event) => change('hapticsEnabled', event.target.checked)} /></label><label><span>顯示拖曳提示</span><input type="checkbox" checked={settings.showSelectionHelp} onChange={(event) => change('showSelectionHelp', event.target.checked)} /></label></div><div className="dialog-actions"><button type="button" className="text-button" onClick={onTutorial}>再次查看教學</button><button type="button" className="text-button" onClick={onAbout}>關於遊戲</button><button type="button" className="danger-button" onClick={onClearStatistics}>清除遊戲紀錄</button></div></OverlayDialog>
}
